falcon-installer:
  size: 81318072
  sha: sha256:b1dedda29694b5e4cc74eb17e80bb48c1f59e3061907f8cf3e85ae11e78d6f63
falcon-installer.exe:
  size: 83260416
  sha: sha256:ab1f475d97a2ae4eb982a4f430005f72abd91769696707fa464e037141565f5e
